### ISSUE TITLE
command blocks --> return barter items?

### ISSUE THREAD

**Issue by acewhite1010** [DuncanRuns/Seed-Based-RNG-Fabric#2]
[vid link](https://streamable.com/n8cltb)
recreate: get sbrng on, 1.16.1
gib command block and throw
idk, is this a wont-fix? felt weird and bamboozled me for a sec so here we are

**Comment by DuncanRuns** [comment]
This mod is a datapack packed into a fabric mod, and is the same datapack that has been used for countless tournaments.

Part of controlling piglin barters is that I need to use commands to actually produce seed based results, so to detect piglin barters, I replaced their loot table with a command block (which is not obtainable in survival) and then I can detect items with data matching the command block items and replace them.

**Comment by DuncanRuns** [comment]
Also I recommend using https://github.com/DuncanRuns/Seed-Cycle-Mod

Just a far better mod with more features and it's all editing actual minecraft code meaning it isn't a weird datapack work-around
